/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32g070xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define GPIOA_EN (1U << 0)
#define GPIOC_EN (1U << 2)

#define GPIOA_MODE (1U << 10)
#define GPIOA_MASK ~(1U << 11)

#define GPIOC_MODE ~(3 << 26)
#define GPIOA5 (1U << 5)

int main(void)
{
	/* enable clock on bus for GPIOA and GPIOC */
	RCC->IOPENR |= GPIOA_EN;
	RCC->IOPENR |= GPIOC_EN;

	/* GPIOA configuration */
	GPIOA->MODER |= GPIOA_MODE;
	GPIOA->MODER &= GPIOA_MASK;

	/* GPIOC configuration */
	GPIOC->MODER &= GPIOC_MODE; //configure c13 as output
	GPIOC->PUPDR &= ~(3U << 26); //ensure no pull up or pull down
	/* Loop forever */q
	for(;;){
		/**
		 * PC13 has a pull up resistor, so it'll be active high when the button isn't pressed.
		 */
		int result = GPIOC->IDR & (1U << 13);
		if (!result) {
			GPIOA->ODR |= GPIOA5;
		} else{
			GPIOA->ODR &= ~GPIOA5;
		}
	}
}
